[buildPlans.IosevkaPrime]
family = "Iosevka Prime"
spacing = "normal" # "quasi-proportional" "term"
serifs = "sans" # "slab"
noCvSs = true # OpenType Features
exportGlyphNames = false # Used for Kitty terminal apparently
noLigation = false # can set this to true for no lig builds

[buildPlans.IosevkaPrime.variants.design]
underscore = "low"
at = "fourfold-tall"
percent = "rings-continuous-slash"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.IosevkaPrime.ligations]
  inherits = "dlig"

# npm run build -- contents::IosevkaPrime
# npm run build -- ttf::IosevkaPrime
# npm run build -- ttf-unhinted::IosevkaPrime

# https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md