"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$python\
$java\
$kotlin\
$haskell\
$elixir\
$python\
$docker_context\
$guix_shell\
$nix_shell\
$line_break\
$character
"""

[os]
disabled = false
style = "blue"

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
SUSE = " "
Ubuntu = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "bright-green"
style_root = "bright-red"
format = '[ $user ]($style)'

[directory]
style = "bright-blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "yellow"
format = '[[ $symbol $branch ](yellow)]($style)'

[git_status]
style = "yellow"
format = '[[($all_status$ahead_behind )](yellow)]($style)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[hostname]
ssh_symbol = " "

[package]
symbol = "󰏗 "

[nix_shell]
symbol = " "

[guix_shell]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[ocaml]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "
style = "green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bright-red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[zig]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[golang]
symbol = " "
style = "cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = " "
style = "magenta"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = " "
style = "magenta"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = " "
style = "yellow"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = " "
style = "bright-blue"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'
vimcmd_symbol = '[Λ](bold green)'
vimcmd_replace_one_symbol = '[Λ](bold purple)'
vimcmd_replace_symbol = '[Λ](bold purple)'
vimcmd_visual_symbol = '[Λ](bold yellow)'
