#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ration 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a brave desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
