live_config_reload = true

import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/gruvbox-dark.toml",
  # "~/.config/alacritty/gruvbox-light.toml"
]

[shell]
program = "zsh"

[window]
padding = { x = 10, y = 10 }
# decorations = "None"
opacity = 1

[font]
size = 16.0

[font.bold]
family = "IosevkaPrimeTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaPrimeTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaPrimeTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaPrimeTerm Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
